//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FourRoads.NAnt.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FourRoads.NAnt.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;project name=&quot;FourRoads.NAnt&quot; default=&quot;help&quot;&gt;
        ///	&lt;description&gt;Dummy build file for the FourRoads.NAnt.Tests project&lt;/description&gt;
        ///	
        ///	&lt;property name=&quot;nant.onfailure&quot; value=&quot;fail&quot; /&gt;
        ///	
        ///	&lt;target name=&quot;fail&quot;&gt;
        ///		&lt;!-- Enter tasks for fail target --&gt;
        ///		&lt;echo message=&quot;Fail target not implemented.&quot; /&gt;
        ///	&lt;/target&gt;
        ///
        ///	&lt;target name=&quot;help&quot;&gt;
        ///		&lt;echo message=&quot;The skeleton file for the build process is designed to execute the following targets in turn:&quot; /&gt;
        ///	&lt;/target&gt;
        ///	
        ///&lt;/p [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string build {
            get {
                return ResourceManager.GetString("build", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;trees&gt;
        ///	&lt;tree name=&quot;ExecuteTaskWithDeletionsTest&quot;&gt;
        ///		&lt;source&gt;
        ///			&lt;directory name=&quot;SubDirectory1&quot;&gt;
        ///				&lt;directory name=&quot;SubSubDirectory2&quot;&gt;
        ///					&lt;file name=&quot;File1.txt&quot; /&gt;
        ///					&lt;file name=&quot;File2.txt&quot; /&gt;
        ///				&lt;/directory&gt;
        ///			&lt;/directory&gt;
        ///			&lt;directory name=&quot;SubDirectory3&quot;&gt;
        ///				&lt;directory name=&quot;SubSubDirectory2&quot;&gt;
        ///					&lt;file name=&quot;File2.txt&quot; /&gt;
        ///				&lt;/directory&gt;
        ///			&lt;/directory&gt;
        ///			&lt;file name=&quot;File2.txt&quot; /&gt;
        ///		&lt;/source&gt;
        ///		&lt;destination&gt;
        ///			&lt;directory name=&quot;Sub [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string trees {
            get {
                return ResourceManager.GetString("trees", resourceCulture);
            }
        }
    }
}
